language: go
sudo: required
services:
  - docker

env:
  global:
    - APP_NAME=raphanus
    - CURRENT_GO_VERSION="1.8"

go:
  - 1.7.x
  - 1.8.x
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/philwinder/gocoverage
  - go get github.com/kisielk/errcheck

install: go get -t ./...

script:
  - go test -race -v ./...
  - go vet ./...
  - errcheck ./...
  - diff <(gofmt -d . server client common) <(echo -n "")
  - if [[ $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION ]]; then
      gocoverage && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi

after_success:
  - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION ]] && [[ $TRAVIS_EVENT_TYPE == "push" || ! -z $TRAVIS_TAG ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$(echo $DOCKER_PASSWORD | base64 -d)" &&
      docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io &&
      docker run --rm -v $PWD:/go/src/$APP_NAME -w /go/src/$APP_NAME golang:alpine sh -c "apk add --no-cache git && go get ./... && go build -ldflags='-w -s' -o ${APP_NAME}-server ./server" &&
      docker build -t $DOCKER_USERNAME/$APP_NAME:latest . &&
      docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:latest &&
      docker push $DOCKER_USERNAME/$APP_NAME:latest &&
      docker push quay.io/$DOCKER_USERNAME/$APP_NAME:latest;
      if [[ ! -z $TRAVIS_TAG ]]; then
        docker tag $DOCKER_USERNAME/$APP_NAME:latest $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG;
      fi;
      rm -f ${APP_NAME}-server;
    fi
