name: Publish Docker image

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/raphanus
          tags: |
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/raphanus:latest

      - name: Push Tag to Docker Hub
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'release' }}
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6
          push: true
          tags: ${{ steps.meta.outputs.tags }}
